# dipdup: ignore
# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Ledger(BaseModel):
    class Config:
        extra = Extra.forbid

    approvals: Dict[str, str]
    balance: str


class Fa1TokenStorage(BaseModel):
    class Config:
        extra = Extra.allow

    # admin: str
    # ledger: Dict[str, Ledger]
    paused: bool
    totalSupply: str
