# generated by datamodel-codegen:
#   filename:  Swap.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SwapParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    MinimumTokenOut: str
    recipient: str
    requiredTokenAddress: str
    requiredTokenId: str
    tokenAmountIn: str
