# generated by datamodel-codegen:
#   filename:  AddLiquidity.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class AddLiquidityParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    recipient: str
    token1_max: str
    token2_max: str
