# generated by datamodel-codegen:
#   filename:  RemoveLiquidity.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RemoveLiquidityParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    lpAmount: str
    recipient: str
    token1_min: str
    token2_min: str
